### ISSUE TITLE
Not work on Postgres

### ISSUE THREAD

**Issue by finzaiko** [cismet/sq-belle#4]
I really like this plugin, everything code the function or procedure inside netbeans, when I try make a postgres function not work correctly that will convert into one line, This would be better if we can make pretty format like plpgsql function.

**Comment by NoorKhan** [comment]
I have the same problem with PL/SQL. I don't think this formats anything other than pure SQL (DDL, DML, etc).

**Comment by helllth** [comment]
will try to fix it. stay tuned a update will be there soon

**Comment by helllth** [comment]
Will try to get rid of the online service to reformat the stuff. Instead try the hibernate BasicFormatter. It would be cool if you guys ( @NoorKhan and @finzaiko ) could give us feedback.

**Comment by helllth** [comment]
New version released. :-)
